export const TIRE_BRANDS = [
  "Michelin",
  "Goodyear",
  "Bridgestone",
  "Pirelli",
  "Continental",
  "Other",
];

export const VEHICLE_MAKES = [
    "Acura",
    "Audi",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Ford",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Mazda",
    "Mercedes-Benz",
    "Nissan",
    "Ram",
    "Subaru",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Other"
];

export const VEHICLE_MODELS: { [key: string]: string[] } = {
    "Acura": ["ILX", "TLX", "RLX", "MDX", "RDX"],
    "Audi": ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7"],
    "BMW": ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5"],
    "Buick": ["Encore", "Envision", "Enclave"],
    "Cadillac": ["CT4", "CT5", "XT4", "XT5", "XT6", "Escalade"],
    "Chevrolet": ["Spark", "Malibu", "Impala", "Equinox", "Traverse", "Tahoe", "Silverado"],
    "Chrysler": ["300", "Pacifica"],
    "Dodge": ["Charger", "Challenger", "Durango"],
    "Ford": ["Fiesta", "Focus", "Fusion", "Mustang", "Escape", "Explorer", "F-150"],
    "GMC": ["Terrain", "Acadia", "Yukon", "Sierra"],
    "Honda": ["Fit", "Civic", "Accord", "HR-V", "CR-V", "Pilot", "Odyssey"],
    "Hyundai": ["Accent", "Elantra", "Sonata", "Kona", "Tucson", "Santa Fe"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80"],
    "Jaguar": ["XE", "XF", "F-PACE", "E-PACE"],
    "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler"],
    "Kia": ["Rio", "Forte", "Optima", "Seltos", "Sportage", "Sorento", "Telluride"],
    "Land Rover": ["Discovery Sport", "Range Rover Evoque", "Range Rover Velar", "Range Rover"],
    "Lexus": ["IS", "ES", "GS", "NX", "RX", "GX", "LX"],
    "Lincoln": ["Corsair", "Nautilus", "Aviator", "Navigator"],
    "Mazda": ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE"],
    "Nissan": ["Versa", "Sentra", "Altima", "Maxima", "Kicks", "Rogue", "Murano", "Pathfinder", "Titan"],
    "Ram": ["1500", "2500", "3500"],
    "Subaru": ["Impreza", "Legacy", "Crosstrek", "Forester", "Outback", "Ascent"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y"],
    "Toyota": ["Yaris", "Corolla", "Camry", "Avalon", "RAV4", "Highlander", "4Runner", "Tacoma", "Tundra"],
    "Volkswagen": ["Jetta", "Passat", "Tiguan", "Atlas"],
    "Volvo": ["S60", "S90", "XC40", "XC60", "XC90"],
    "Other": ["Other"]
};

export const COMMON_TIRE_SIZES = [
    "225/45R17",
    "215/55R17",
    "235/65R17",
    "205/55R16",
    "195/65R15",
    "245/45R18",
    "275/55R20",
    "265/70R17",
    "Other"
];
