-- This script is intended for manual execution in the Supabase SQL Editor
-- if automatic migrations fail.

-- 1. Create the 'users' table to store user information
CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying,
    role character varying DEFAULT 'member'::character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

DO $$
BEGIN
   IF NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conname = 'users_pkey' AND conrelid = 'public.users'::regclass
   ) THEN
       ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
   END IF;
END;
$$;

DO $$
BEGIN
   IF NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conname = 'users_email_key' AND conrelid = 'public.users'::regclass
   ) THEN
       ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);
   END IF;
END;
$$;


-- 2. Create the 'policies' table for warranty data
CREATE TABLE IF NOT EXISTS public.policies (
    "policyNumber" character varying NOT NULL,
    "customerName" text,
    "customerEmail" text,
    "customerPhone" text,
    "tireDot" text,
    "purchaseDate" date,
    "warrantyEndDate" date,
    "receiptUrl" text,
    "policyDocument" text,
    "vehicleYear" integer,
    "vehicleMake" text,
    "vehicleModel" text,
    "vehicleMileage" integer,
    "dealerName" text,
    "invoiceNumber" text,
    "roadHazardPrice" numeric,
    "pricePerTire" numeric,
    "tireQuantity" integer,
    "tireDot1" text,
    "tireDot2" text,
    "tireDot3" text,
    "tireDot4" text,
    "tireDot5" text,
    "tireDot6" text,
    "customerStreet" text,
    "customerCity" text,
    "customerState" text,
    "customerZip" text,
    "vehicleSubmodel" text,
    "isCommercial" boolean,
    "tireBrand" text,
    "tireModel" text,
    "tireSize" text,
    "created_at" timestamp with time zone DEFAULT now()
);

DO $$
BEGIN
   IF NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conname = 'policies_pkey' AND conrelid = 'public.policies'::regclass
   ) THEN
       ALTER TABLE public.policies ADD CONSTRAINT policies_pkey PRIMARY KEY ("policyNumber");
   END IF;
END;
$$;

-- 3. Enable Row Level Security (RLS) on the tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.policies ENABLE ROW LEVEL SECURITY;

-- 4. Set up Storage: Create the 'receipts' bucket
-- This command is idempotent, it won't fail if the bucket already exists.
INSERT INTO storage.buckets (id, name, public)
VALUES ('receipts', 'receipts', true)
ON CONFLICT(id) DO NOTHING;
