-- 1. Create the 'claims' table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.claims (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    claim_details text,
    status character varying DEFAULT 'pending'::character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Add 'id' as a primary key if it's not already
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'claims_pkey' AND conrelid = 'public.claims'::regclass
    ) THEN
        ALTER TABLE public.claims ADD CONSTRAINT claims_pkey PRIMARY KEY (id);
    END IF;
END;
$$;

-- Add 'policy_id' column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'claims' AND column_name = 'policy_id'
    ) THEN
        ALTER TABLE public.claims ADD COLUMN policy_id character varying;
    END IF;
END;
$$;

-- 2. Add foreign key constraint to 'policy_id'
DO $$
BEGIN
   IF NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conname = 'claims_policy_id_fkey' AND conrelid = 'public.claims'::regclass
   ) THEN
       ALTER TABLE public.claims ADD CONSTRAINT claims_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies("policyNumber");
   END IF;
END;
$$;

-- 3. Enable Row Level Security (RLS) on the table
ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;

-- 4. Apply Row Level Security Policies
DROP POLICY IF EXISTS "Allow authenticated users to manage all claims" ON public.claims;
CREATE POLICY "Allow authenticated users to manage all claims"
ON public.claims
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);
